### ISSUE TITLE
There is a problem with the block browser

### ISSUE THREAD

**Issue by uosh27** [starcoinorg/starcoin-explorer#1]
There is a problem with the block browser，we can find nothing use   http://explorer.starcoin.org/search/   
just   http://explorer.starcoin.org/barnard/address/    can find our account address on explorer.

**Comment by wk3368** [comment]
fixed by: https://github.com/starcoinorg/starcoin-explorer/commit/23d893c88a545d4d822c472b1be91b3180ff8e7f
