### ISSUE TITLE
持币者列表页点进去的地址在链上无法查看

### ISSUE THREAD

**Issue by mzcaptainyang** [starcoinorg/starcoin-explorer#102]
如下图所示，地址在列表页可以看到数据，但是点击进去提示 address 不存在：https://stcscan.io/main/address/0x2c9eca568e812e7643f7aa9da8804a19

![image](https://user-images.githubusercontent.com/10356883/132530621-cb2668ae-5d11-4fe8-acf5-0083778a0786.png)
![image](https://user-images.githubusercontent.com/10356883/132530695-4e26158f-034c-4760-abf5-4f365bfc4d98.png)

**Comment by ssyuan** [comment]
查了一下数据，0x2c9eca568e812e7643f7aa9da8804a19 曾经打了一个块，但被分叉回滚了，所以在最新的主链上没有。历史事件没有清理造成holder展示多余了。

**Comment by tarvos21** [comment]
Fixed
