### ISSUE TITLE
持币列表表显示的持币数和地址详情页的持币数对不上

### ISSUE THREAD

**Issue by mzcaptainyang** [starcoinorg/starcoin-explorer#103]
如图所示，持币列表页，显示的持币数是：205,541，但是进入详情页之后，显示的持币数为 0

https://stcscan.io/main/address/0xe11b3a647fe805ce14914432c5995972

![image](https://user-images.githubusercontent.com/10356883/132531980-66ad1573-903e-4acb-a06a-d30bca422adc.png)
![image](https://user-images.githubusercontent.com/10356883/132532032-db45026a-ddf6-4555-980e-3b2b4075314e.png)

**Comment by tarvos21** [comment]
@mzcaptainyang Holder列表数据需要统计来自链上的数据，而地址的详情页数据直接取自链上，所以Holder列表数据会有些延迟，现在已经更正
