### ISSUE TITLE
地址在链上不存在时可以考虑展示一个空账号

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-explorer#113]
现在地址在链上不存在会直接提示用户账号不存在，这个对新用户来说有点不容易理解，以为那个地址不能用。
可以参考 etherscan.io 的做法，任何地址都展示一个余额为 0 的空账号页面，而不是报错。可以理解成账号和地址是链下生成的，只是链上没余额而已。

**Comment by tarvos21** [comment]
Example(link from newly created account address in StarMask wallet):

https://stcscan.io/main/address/0x3bc1b16ae2b294c2e78cba5016624250
