### ISSUE TITLE
[Feature Request] Display module upgrade strategy on the account page

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-explorer#117]
在账号页面展示该账号的升级策略（module upgrade strategy）

Starcoin 的合约（Module）默认是可升级的，并且有不同的升级策略。需要在账号页面展示出该账号的升级策略，这样用户可以通过合约所在账号的升级策略来判断安全性。

关于链上升级的说明参看： https://starcoin.org/zh/developer/blog/starcoin_stdlib_upgrade/

当前有以下几种升级策略：

https://github.com/starcoinorg/starcoin-framework/blob/d2a2fc971babbca869231592a9511045f7fa9875/sources/PackageTxnManager.move#L29

```rust
        const STRATEGY_ARBITRARY: u8 = 0;
        const STRATEGY_TWO_PHASE: u8 = 1;
        const STRATEGY_NEW_MODULE: u8 = 2;
        const STRATEGY_FREEZE: u8 = 3;
```

* ARBITRARY: 开发者直接升级，但需要保证合约的兼容性。
* TWO_PHASE: 两阶段升级，开发者需要先提交升级计划（UpgradePlan），在链上公布 Package Hash，然后再升级，升级时会检查升级的 Package Hash 是否和升级计划中公布的 Hash 一致。
* NEW_MODULE: 只能新增 Module，不能变更已经部署的 Module。
* FREEZE: 冻结，不可新增，也不可升级。

当账号的升级策略变更为 TWO_PHASE 的时候，可以把升级权限托管给 DAO，然后通过 Token 治理机制进行投票升级。

区块浏览器获取账号升级策略的方法：

1. 调用 `0x1::PackageTxnManager::get_module_upgrade_strategy(address)` 只读方法获取该 address 的升级策略。
2. 如果升级策略为 `TWO_PHASE`, 检查该地址下是否有 `0x1::PackageTxnManager::UpgradePlanCapability`，如果有则说明该账号自己掌握两阶段升级的能力，没有则说明代理出去了。
3. 如果没有，则继续检查该地址下是否有 `0x1::UpgradeModuleDaoProposal::UpgradeModuleCapability<T>`(注：T 是治理 Token 泛型参数), 如果有则说明代理给 DAO 了。

总结一下, 如果加上 DAO 升级策略实际上有 5 种：

1. ARBITRARY 
2. TWO_PHASE
3. TWO_PHASE + DAO（T）
4. NEW_MODULE
5. FREEZE

另外希望能单独过滤出升级交易（Package 类型的交易）以及提交升级计划的交易（这个需要增加一个新的 Event 进行过滤，可以下期再做 https://github.com/starcoinorg/starcoin-framework/issues/11 ），这样方便社区用户监督项目方的变更。

**Comment by ssyuan** [comment]
初步拆解一下任务：
1、前端：
          获取地址的升级策略：0x1::PackageTxnManager::get_module_upgrade_strategy(address)，如果有返回则继续：
          读取account的state，（state.get_resource即可），判断UpgradePlanCapability ，UpgradeModuleCapability分别展示
     预留一个链接：将来可以点击后，展示升级/以及升级计划的交易
2、api端：
     提供升级交易接口
     提供升级计划交易接口

**Comment by tarvos21** [comment]
@jolestar 有没有5个不同策略的账号？我验证一下是否正确

**Comment by jolestar** [comment]
> @jolestar 有没有5个不同策略的账号？我验证一下是否正确

1. 默认是 ARBITRARY
2. 0x1 是  TWO_PHASE + DAO（STC）
3. NEW_MODULE，FREEZE 还没有，可以调用更新升级策略的方法来构造。 0x1::ModuleUpgradeScripts::update_module_upgrade_strategy

**Comment by tarvos21** [comment]
@jolestar 现在有个问题，查询resource时，`0x1::UpgradeModuleDaoProposal::UpgradeModuleCapability<T>`，这里面的'<T>'无法传进去，提示parse error

**Comment by jolestar** [comment]
> @jolestar 现在有个问题，查询resource时，`0x1::UpgradeModuleDaoProposal::UpgradeModuleCapability<T>`，这里面的`<T>`无法传进去，提示parse error

这个 T 必须是一个 Token 类型，比如 `0x1::STC::STC`. 但如果不知道是什么类型，感觉得 list resource 然后过滤。

**Comment by jolestar** [comment]
如果 list resource 实现效率比较低，这项可以延期，考虑提供一个设置项目（指定 DAO 以及治理 Token），这个设置用户自己也可以提交，提交时通过链上数据校验一下就可以。

**Comment by ssyuan** [comment]
@tarvos21 
升级交易的接口已经ok，txn_type=2就是package类型，默认是0，是所有，1：script，3：script-fun
https://api.stcscan.io/swagger-ui/#/transaction/getRangeByAddressAliasUsingGET

**Comment by tarvos21** [comment]
> 如果 list resource 实现效率比较低，这项可以延期，考虑提供一个设置项目（指定 DAO 以及治理 Token），这个设置用户自己也可以提交，提交时通过链上数据校验一下就可以。

那我先把0，1(two phase)，2，3，四种基本类型展示出来了

**Comment by tarvos21** [comment]
> 

好的，收到
