### ISSUE TITLE
AWW token circulating supply bug

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-explorer#120]
![image](https://user-images.githubusercontent.com/77268/162436828-0a324ac7-344a-4237-ad9a-623b554a8030.png)

![image](https://user-images.githubusercontent.com/77268/162436856-3ac84e25-8fe0-47eb-9003-8f08210312fb.png)

The AWW token balance in a user's wallet > stcscan's circulating supply.
Maybe it is a precision bug, StarMask wallet does not use the same precision as stcscan, one of the two has this bug.

**Comment by uvd** [comment]
wallet fix
