### ISSUE TITLE
关于transacition的detail页面, ScriptFunction的参数写死的问题

### ISSUE THREAD

**Issue by wk3368** [starcoinorg/starcoin-explorer#13]
我们讨论过这个参数写死的问题，
最好是加一个参数显示配置的map，大概是这样： {函数名，参数map:{参数1: filedName, 参数2: fieldName}}
但是这就回到一个常见的问题：这个map目前还没有整理出来，而且是前端修改还是后端修改的问题
因为现在explorer-api 只是很简单的一层对es的查询封装，没有做任何处理就返回给前端了。

我们现在想得是，这是个重要不紧急的问题，可以等后面有时间再来优化，现在先这样实现效果。

_Originally posted by @wk3368 in https://github.com/starcoinorg/starcoin-explorer/pull/12#discussion_r614508531_

**Comment by wk3368** [comment]
可以考虑根据这个文档: https://github.com/starcoinorg/starcoin-vs-ethereum-rpc
整理出ScriptFunction的参数map，然后放在前端里面。

explorer-api可以保动，保持足够轻量化。

**Comment by jolestar** [comment]
这个每个 ScriptFunction 都是不一样的，并且可以用户自定义。所以最好是通过 ABI 动态探测，参数名以及参数类型。

**Comment by wk3368** [comment]
> 这个每个 ScriptFunction 都是不一样的，并且可以用户自定义。所以最好是通过 ABI 动态探测，参数名以及参数类型。

主要是这个参数在 xhr的请求response的json里面的路径，类似'result.xxx.xxx.xxx'， 需要人工整理。

**Comment by jolestar** [comment]
> > 这个每个 ScriptFunction 都是不一样的，并且可以用户自定义。所以最好是通过 ABI 动态探测，参数名以及参数类型。
> 
> 主要是这个参数在 xhr的请求response的json里面的路径，类似'result.xxx.xxx.xxx'， 需要人工整理。

人工整理肯定不太靠谱，只能整理 stdlib 中的几个。这个不能作为一个 map 直接遍历么？

**Comment by wk3368** [comment]
> 人工整理肯定不太靠谱，只能整理 stdlib 中的几个。这个不能作为一个 map 直接遍历么？

这个response的json是从es里面query返回的，我说的人工整理是指的这个，需要得从es的返回结果里面找到需要的field在整个response的大json里面的具体路径。
