### ISSUE TITLE
[功能增强]搜索框固定展示

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin-explorer#141]
浏览器提供了一个通用的搜索功能，但只在首页展示，建议固定到顶部导航栏，这样在任何页面都可以进行搜索。
如图所示，将红框标注的搜索框，置顶到绿框位置。
![image](https://user-images.githubusercontent.com/537535/170209975-da1c26d1-5f2a-4554-a3c8-8b3130b7df3e.png)

**Comment by uvd** [comment]
#143  当不上处于首页的时候 顶部搜索栏就会出现
