### ISSUE TITLE
关于区块浏览器的小建议

### ISSUE THREAD

**Issue by ggdi** [starcoinorg/starcoin-explorer#16]
建议将区块浏览器修改成自动更新，当页面静止时也能实时看到区块的更新信息。不仅更加方便，也更符合其他主流区块浏览器的使用习惯。希望再加个能够把页面设置为暗色主题的模式。

最后是否可以再加个https的证书

下面的截图来自ETH区块浏览器
![QQ截图20210428225028](https://user-images.githubusercontent.com/46952001/116426137-6d1a1d00-a875-11eb-9853-d964a3e2fd9c.jpg)

**Comment by jolestar** [comment]
https 已经支持，自动更新这个还需要时间开发

**Comment by ggdi** [comment]
> https已经支持，自动更新这个还需要时间开发

**Comment by ggdi** [comment]
> https已经支持，自动更新这个还需要时间开发

**Comment by ggdi** [comment]
感谢，非常有效率，期待更多的更新

**Comment by tw7613781** [comment]
made a PR regarding to block list and tx list auto update. 
https://github.com/starcoinorg/starcoin-explorer/pull/27
