### ISSUE TITLE
用户账号下 Token 信息展示的问题

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-explorer#164]
1. Token 需要有办法给用户展示 Token 的全地址，否则容易出现 Token 骗局。Token 可以带一个链接，指向一个具体的 Token Info 页面（这个当前还没有）。
2. Token 的精度不对，比如截图中的 XETH

<img width="873" alt="Screen Shot 2022-06-09 at 23 11 24" src="https://user-images.githubusercontent.com/77268/172986754-eba302bb-0609-4f09-b9d0-40ed948a3416.png">

**Comment by uvd** [comment]
#165
