### ISSUE TITLE
浏览器页面无法查看接受转账交易详情

### ISSUE THREAD

**Issue by ggdi** [starcoinorg/starcoin-explorer#18]
当从A地址发送STC到B地址时，A地址页面可以查询到发送的txid，但是B地址页面无法查询历史接受STC的txid。
建议增加查看地址历史接受信息。

**Comment by jolestar** [comment]
这个当前还不太好实现，starcoin 的交易都是执行合约，判断 sender 比较容易，判断 receiver 比较难。不过可以考虑展示 WithdrawEvent 和 DepositEvent

**Comment by tarvos21** [comment]
账户页面的交易列表已经包含发送和接受的交易
