### ISSUE TITLE
[bug] 无法搜索到，或者展示通过starmask创建的新账户

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin-explorer#186]
**步骤**
1. starmask新建一个账户
2. 点击view in explorer， 如图
![image](https://user-images.githubusercontent.com/23182033/178178025-a2ca8018-4389-4665-be20-4856f5e2f491.png)

**现象**

会发现页面标题是not on chain；Authentication Key之类的数据都是空的，地址https://stcscan.io/main/address/0xf7da150096158346dc4a033a48e54ebf
![image](https://user-images.githubusercontent.com/23182033/178178154-c8c89908-4b16-4dec-b53b-fa6f6dffa768.png)

搜索时404，https://stcscan.io/search/0xf7da150096158346dc4a033a48e54ebf
![image](https://user-images.githubusercontent.com/23182033/178178359-cfb5e28c-fe42-4b10-90a7-18a53db11fd3.png)

**更多细节**
只要有一笔交易，上面的问题会消失，否则无论过多久都查不到这个账户的数据

可能是链上（ https://main-seed.starcoin.org/ ）获取账户信息的api的问题，先把现象在这里记录一下

**Comment by uvd** [comment]
没有任何资源的地址是不是还没上链，交易一下，才会上链

**Comment by uvd** [comment]
不算bug 先关闭
