### ISSUE TITLE
[bug] 【持仓占比】有误

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin-explorer#187]
https://stcscan.io/main/tokens/holders/0x2b547120e3c36deac1d6c93dca8c4d40::JY001t::JY001t/1
持仓占比超过了100%
![image](https://user-images.githubusercontent.com/23182033/179003059-94af0d11-319c-4b30-8a81-953f3904dbec.png)

------------补充信息----------------

看上去直接从返回的数据计算的
api: https://api.stcscan.io/v2/token/main/holders/page/1?token_type=0x2b547120e3c36deac1d6c93dca8c4d40::JY001t::JY001t
```json
{
	"contents":[
		{
			"address":"0x308f50dadff30762b138746cde7b7d53",
			"amount":123456789990000000,
			"supply":23400000000000
		},
		{
			"address":"0x2f54c3aed0f0c783ad48c83601d53914",
			"amount":1000965441000000,
			"supply":23400000000000
		},
		{
			"address":"0x2b547120e3c36deac1d6c93dca8c4d40",
			"amount":33000000,
			"supply":23400000000000
		}
	],
	"total":3
}
```

**Comment by uvd** [comment]
这个是后端的数据没处理对这个的精度 前面我反馈过

**Comment by jiangying000** [comment]
看起来好了
