### ISSUE TITLE
transactions 页面，url中的页数和实际页数不对应

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin-explorer#188]
## 描述1：
从首页顶栏点击transaction，会打开：https://stcscan.io/main/transactions/1
随意翻页，发现url中的页数一直是1
![image](https://user-images.githubusercontent.com/23182033/179390866-4eec172f-d8d3-4629-b5b8-235474ac82e7.png)

## 描述2：
直接打开：https://stcscan.io/main/transactions/100
发现仍然是第一页的结果

**Comment by uvd** [comment]
#196
