### ISSUE TITLE
token Position Ratio 显示 Infinity%

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin-explorer#199]
https://stcscan.io/main/tokens/holders/0x2b547120e3c36deac1d6c93dca8c4d40::Attat::Attat/1

![image](https://user-images.githubusercontent.com/23182033/181405709-4e29786c-b28f-4a88-9154-7f4901c0432e.png)

关联：https://github.com/starcoinorg/starcoin-search/issues/55

**Comment by ssyuan** [comment]
已经修复，感谢反馈
