### ISSUE TITLE
block页面中展示 block reward

### ISSUE THREAD

**Issue by fikgol** [starcoinorg/starcoin-explorer#40]

**Comment by jolestar** [comment]
block reward 在 event 中，只要实现了 #22 这个，应该就可以展示 reward

**Comment by jolestar** [comment]
{"block_number":"221119","block_reward":"5000000000","gas_fees":"0","miner":"0x3b8ebb9e889f8df0b603d8d9f3f05524"}

现在看来已经展示出来了
