### ISSUE TITLE
提供一个 web 工具转换 Address 和 Receipt Identifier

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-explorer#42]
可参考 account receipt-identifer 命令

**Comment by tarvos21** [comment]
Address 可以从 Receipt Identifier 转换出来，但 Receipt Identifier 需要用户直接提供私钥。之前出于用户体验考虑，尽可能避免让用户直接在页面端提供私钥，所以我觉得，是否仅提供从 Receipt Identifier 转换出 Address 的功能？

@jolestar

**Comment by jolestar** [comment]
不需要私钥。可以参看 cli 命令

**Comment by wk3368** [comment]
starcoin.js 已经提供了两个函数来实现这两个需求：

1. encoding.encodeReceiptIdentifier: address -> receiptIdentifier
2. encoding.decodeReceiptIdentifier: receiptIdentifier -> address

例子可以参考:
https://github.com/starcoinorg/starcoin.js/blob/master/src/encoding/index.spec.ts#L156

**Comment by tarvos21** [comment]
> 不需要私钥。可以参看 cli 命令

ok, 可以用 public key 得到 receipt identifier
