### ISSUE TITLE
查看地址信息，主网和测试网链接展示反了

### ISSUE THREAD

**Issue by fanngyuan** [starcoinorg/starcoin-explorer#49]
区块浏览器提个 BUG，查看地址信息，主网和测试网链接展示反了。

https://explorer.starcoin.org/barnard/address/0x1ff4fc74d30f8bdfdddbcbf27c5a59b3

https://explorer.starcoin.org/main/address/0x1ff4fc74d30f8bdfdddbcbf27c5a59b3

**Comment by wk3368** [comment]
@zzfScarecrow  
这个问题和#50 一样 都是 cookie里面的network 优先级 比 路径里面的network要高 造成的！
可以一起fix！
