### ISSUE TITLE
用户账号交易列表数据一致性问题

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-explorer#58]
有的交易在列表无法看到，比如 https://explorer.starcoin.org/main/address/0xb2aa52f94db4516c5beecef363af850a 地址

<img width="1239" alt="Screen Shot 2021-07-03 at 18 16 00" src="https://user-images.githubusercontent.com/77268/124351138-2f49c400-dc2b-11eb-9274-589f15f8335c.png">

而 https://explorer.starcoin.org/main/transactions/detail/0xdc55518a6173904c28be418ed665a34f533a75e36307cbb6e0dfc42279489b98 这个交易的 sequence number 是 21，而该账号的 sequence number 当前为 25

**Comment by ssyuan** [comment]
找到原因，是过滤事件少了ProposalCreatedEvent，这个用户下有三个：比如下面的交易也是这个用户的：
https://stcscan.io/main/transactions/detail/0x299b901b998b54d46e71edda46663fc62d8168f5dea24c2dbd05a7813f42d889

**Comment by jolestar** [comment]
> 找到原因，是过滤事件少了ProposalCreatedEvent，这个用户下有三个：比如下面的交易也是这个用户的：
> https://stcscan.io/main/transactions/detail/0x299b901b998b54d46e71edda46663fc62d8168f5dea24c2dbd05a7813f42d889

不应该用 event 过滤，不可能穷举 event。应该把 sender 等于当前用户的全列出来，其他的和当前用户相关的交易，比如收款（DepositEvent），单独展示。
