### ISSUE TITLE
交易时间显示有问题

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin-explorer#64]
![1625796933636](https://user-images.githubusercontent.com/537535/125013720-e9fc1b00-e09e-11eb-8b4c-9a185b6ff267.jpg)
历史交易，显示just now

**Comment by wk3368** [comment]
https://stcscan.io/main/blocks/detail/0x4704105602714908667c811fc119c58cdbbb3618fcfe43eb4d8e93e8f126ce76
