### ISSUE TITLE
页面跳转链接问题

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin-explorer#67]
![202179-15138](https://user-images.githubusercontent.com/537535/125038619-33ad2b80-e0c8-11eb-8ef0-5fec2347e580.png)
点击ecosystems，再点击block，会出现上面的URL，其他二级菜单也类似，应该是一个问题

**Comment by wk3368** [comment]
fixed by https://github.com/starcoinorg/starcoin-explorer/pull/71
