### ISSUE TITLE
TOKENS list 分页不生效，每页数据都一样、且页码有误

### ISSUE THREAD

**Issue by jiangydev** [starcoinorg/starcoin-explorer#87]
页面地址：https://stcscan.io/main/tokens/3

问题描述：
1. 分页不生效，每页数据都和第一页一样；
2. 页码也有问题，第一页是 1-6，第二页是 21-26；

问题截图：
![image](https://user-images.githubusercontent.com/25546833/130320964-ef86a2fc-12f7-4510-aed4-a362cbafa6ba.png)

**Comment by tarvos21** [comment]
Fixed. Thanks for the issue!
