### ISSUE TITLE
超时交易在barnard节点上查询时会空白页

### ISSUE THREAD

**Issue by muzixinly** [starcoinorg/starcoin-explorer#90]
https://stcscan.io/barnard/transactions/detail/0x755f932899cff1392db1fae2d2e9f7b9192116726b5a206e11789229c4649d3b

例如这个交易，由于超时被取消，查看chrome调试工具，能看到报错接口。

**Comment by tarvos21** [comment]
另一个出现错误的交易：
[](https://stcscan.io/main/transactions/detail/0x2d3254d8479a0e4b50a773f424222e32e4d3c27ba508a7c0eb0d930d9bd2e8f1)
