### ISSUE TITLE
Token 精度问题

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-explorer#95]
展示 Token 余额的时候使用的精度不对，不是 Token 内部定义的精度

https://stcscan.io/main/tokens/detail/0x06198e0fc6d13a171ff1c1c10549451d::BX_USDT::BX_USDT

```
state get resource 0x06198e0fc6d13a171ff1c1c10549451d 0x1::Token::TokenInfo<0x06198e0fc6d13a171ff1c1c10549451d::BX_USDT::BX_USDT>
{
  "ok": {
    "raw": "0x00008d49fd1a07000000000000000000e8030000000000000000000000000000010000000000000018090000000000000006198e0fc6d13a171ff1c1c10549451d0000000000000000180a0000000000000006198e0fc6d13a171ff1c1c10549451d",
    "json": {
      "total_value": 2000000000000000,
      "scaling_factor": 1000,
      "mint_events": {
        "counter": 1,
        "guid": "0x090000000000000006198e0fc6d13a171ff1c1c10549451d"
      },
      "burn_events": {
        "counter": 0,
        "guid": "0x0a0000000000000006198e0fc6d13a171ff1c1c10549451d"
      }
    }
  }
}
``` 

BX_USDT 的 scaling_factor 是 1000

https://stcscan.io/main/tokens/detail/0x06198e0fc6d13a171ff1c1c10549451d::BX_USDT::BX_USDT

<img width="1233" alt="Screen Shot 2021-08-27 at 17 35 04" src="https://user-images.githubusercontent.com/77268/131106609-ee8649ef-4493-4a14-af4f-cef0d04431ac.png">

**Comment by timyangnet** [comment]
这个页面也一样，请尽快加上小数点，避免用户带来困惑（及误解增发恐慌）
https://stcscan.io/main/tokens/1
![image](https://user-images.githubusercontent.com/3723450/131456085-1a802417-9c59-4b4a-9d36-e75fa324a517.png)

**Comment by tarvos21** [comment]
```
{
 "id":101, 
 "jsonrpc":"2.0", 
 "method":"contract.call_v2", 
 "params": [
      {
        "function_id": "0x1::Token::scaling_factor",
        "type_args": ["0x9350502a3af6c617e9a42fa9e306a385::BX_USDT::BX_USDT"],
        "args": []
     
     }
   ]
}
```

@jolestar 用上面的接口获取scaling_factor，得到的是100000000，其他代币都是一样的，scaling_factor数据是否有误？

**Comment by jolestar** [comment]
> ```
> {
>  "id":101, 
>  "jsonrpc":"2.0", 
>  "method":"contract.call_v2", 
>  "params": [
>       {
>         "function_id": "0x1::Token::scaling_factor",
>         "type_args": ["0x9350502a3af6c617e9a42fa9e306a385::BX_USDT::BX_USDT"],
>         "args": []
>      
>      }
>    ]
> }
> ```
> 
> @jolestar 用上面的接口获取scaling_factor，得到的是100000000，其他代币都是一样的，scaling_factor数据是否有误？

这是新发的一个 Token 吧。以链上数据为准保持一致就行。

**Comment by tarvos21** [comment]
Token list, token info, token holder list数据小数点位置及名称已经更新
