### ISSUE TITLE
Tokens Holder 页面在手机端不显示持币人地址

### ISSUE THREAD

**Issue by mzcaptainyang** [starcoinorg/starcoin-explorer#96]
https://stcscan.io/main/tokens/holders/0x00000000000000000000000000000001::STC::STC/1

如下图所示，持币人列表页面，在手机端不显示持币人地址

![image](https://user-images.githubusercontent.com/10356883/131439391-2c71b37a-50e8-4e9c-85e1-f2fd20960754.png)

**Comment by tarvos21** [comment]
Fixed. Thanks for the issue!
